### ISSUE TITLE
Some R packages are failing to install due to a system dependency.

### ISSUE THREAD

**Issue by deflaux** [DataBiosphere/leonardo#710] opened 2018-12-05 22:42 UTC
There are a couple R packages like this, all with the same issue with `gfortran`:

```
R version 3.5.1 (2018-07-02) -- "Feather Spray"
. . .
> install.packages('qwraps2')
Installing package into ‘/home/jupyter-user/.rpackages’
. . .
g++ -std=gnu++11 -shared -L/usr/lib/R/lib -Wl,-z,relro -o RcppArmadillo.so RcppArmadillo.o RcppExports.o fastLm.o -fopenmp-llapack -lblas -lgfortran -lm -lquadmath -L/usr/lib/R/lib -lR
/usr/bin/x86_64-linux-gnu-ld: cannot find -lgfortran
collect2: error: ld returned 1 exit status
/usr/share/R/share/make/shlib.mk:6: recipe for target 'RcppArmadillo.so' failed
make: *** [RcppArmadillo.so] Error 1
ERROR: compilation failed for package ‘RcppArmadillo’
* removing ‘/home/jupyter-user/.rpackages/RcppArmadillo’
ERROR: dependency ‘RcppArmadillo’ is not available for package ‘qwraps2’
* removing ‘/home/jupyter-user/.rpackages/qwraps2’

The downloaded source packages are in
        ‘/tmp/RtmpxXAFVb/downloaded_packages’
Warning messages:
1: In install.packages("qwraps2") :
  installation of package ‘RcppArmadillo’ had non-zero exit status
2: In install.packages("qwraps2") :
  installation of package ‘qwraps2’ had non-zero exit status
>
```

By the way, thanks for the update to R 3.5.1 and all the other updates to the base image!

**Comment by rtitle** [comment] 2018-12-13 21:32
Interesting. We do install `gfortran` in the docker image:
https://github.com/DataBiosphere/leonardo/blob/develop/docker/jupyter/Dockerfile#L231

I wonder R 3.5 somehow broke the dependency..

**Comment by rtitle** [comment] 2018-12-13 22:02
I reproduced Nicole's error. This seemed to fix it on my cluster:
```
sudo ln -s /usr/lib/x86_64-linux-gnu/libgfortran.so.3 /usr/lib/x86_64-linux-gnu/libgfortran.so
```
Install output after fix:
```
R version 3.5.1 (2018-07-02) -- "Feather Spray"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> install.packages('qwraps2')
Installing package into ‘/home/jupyter-user/.rpackages’
(as ‘lib’ is unspecified)
also installing the dependency ‘RcppArmadillo’

trying URL 'https://cloud.r-project.org/src/contrib/RcppArmadillo_0.9.200.5.0.tar.gz'
Content type 'application/x-gzip' length 1314424 bytes (1.3 MB)
==================================================
downloaded 1.3 MB

trying URL 'https://cloud.r-project.org/src/contrib/qwraps2_0.3.0.tar.gz'
Content type 'application/x-gzip' length 87511 bytes (85 KB)
==================================================
downloaded 85 KB

* installing *source* package ‘RcppArmadillo’ ...
** package ‘RcppArmadillo’ successfully unpacked and MD5 sums checked
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ accepts -g... (cached) yes
checking whether g++ version is sufficient... yes, with OpenMP as version 6.5.0
checking for macOS... checking LAPACK_LIBS... system LAPACK found
checking for OpenMP... found and suitable
configure: creating ./config.status
config.status: creating inst/include/RcppArmadilloConfigGenerated.h
config.status: creating src/Makevars
** libs
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/usr/local/lib/R/site-library/Rcpp/include"   -I../inst/include -fopenmp -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c RcppArmadillo.cpp -o RcppArmadillo.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/usr/local/lib/R/site-library/Rcpp/include"   -I../inst/include -fopenmp -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/usr/local/lib/R/site-library/Rcpp/include"   -I../inst/include -fopenmp -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c fastLm.cpp -o fastLm.o
g++ -std=gnu++11 -shared -L/usr/lib/R/lib -Wl,-z,relro -o RcppArmadillo.so RcppArmadillo.o RcppExports.o fastLm.o -fopenmp -llapack -lblas -lgfortran -lm -lquadmath -L/usr/lib/R/lib -lR
installing to /home/jupyter-user/.rpackages/RcppArmadillo/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (RcppArmadillo)
* installing *source* package ‘qwraps2’ ...
** package ‘qwraps2’ successfully unpacked and MD5 sums checked
** libs
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/usr/local/lib/R/site-library/Rcpp/include" -I"/home/jupyter-user/.rpackages/RcppArmadillo/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/usr/local/lib/R/site-library/Rcpp/include" -I"/home/jupyter-user/.rpackages/RcppArmadillo/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c logit.cpp -o logit.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/usr/local/lib/R/site-library/Rcpp/include" -I"/home/jupyter-user/.rpackages/RcppArmadillo/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c traprule.cpp -o traprule.o
g++ -shared -L/usr/lib/R/lib -Wl,-z,relro -o qwraps2.so RcppExports.o logit.o traprule.o -llapack -lblas -lgfortran -lm -lquadmath -L/usr/lib/R/lib -lR
installing to /home/jupyter-user/.rpackages/qwraps2/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (qwraps2)

The downloaded source packages are in
	‘/tmp/RtmpN5V7zS/downloaded_packages’
```

I can make a PR to fix this in the Dockerfile.

**Comment by rtitle** [comment] 2018-12-13 22:13
Hopefully this PR fixes it: https://github.com/DataBiosphere/leonardo/pull/719

Will let tests run and also manually verify.

**Comment by calbach** [comment] 2019-01-04 22:21
This appears to have been fixed with the latest Leo, at least for AoU clusters.

```
install.packages('qwraps2')
library(qwraps2)

Installing package into ‘/home/jupyter-user/.rpackages’
(as ‘lib’ is unspecified)
also installing the dependency ‘RcppArmadillo’
```

**Comment by deflaux** [comment] 2019-05-15 16:25
This appears to have regressed on the AoU workbench. I have not verified this on Terra because I do not want to delete and recreate my Leonardo instance.

From the Jupyter terminal:
```
jupyter-user@all-of-us-m:~$ R

R version 3.5.2 (2018-12-20) -- "Eggshell Igloo"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> install.packages('qwraps2')
Installing package into ‘/home/jupyter-user/.rpackages’
(as ‘lib’ is unspecified)
also installing the dependency ‘RcppArmadillo’

... 

/usr/bin/ld: cannot find -lgfortran
collect2: error: ld returned 1 exit status
/usr/share/R/share/make/shlib.mk:6: recipe for target 'RcppArmadillo.so' failed
make: *** [RcppArmadillo.so] Error 1

...
```

**Comment by Arhodes-Broad** [comment] 2019-06-11 14:16
I had a recurrence of this error, where an R package needed the RcppArmadillo package installed and the gfortran library was not located by the R kernel in the Jupyter notebook.

**Comment by mbookman** [comment] 2019-06-28 17:46
I have run into this as well, 

```
gcc -std=gnu99 -shared -L/usr/lib/R/lib -Wl,-z,relro -o SparseM.so bckslv.o chol.o chol2csr.o cholesky.o csr.o extract.o init.o sparskit.o subscr.o -lgfortran -lm -lquadmath -L/usr/lib/R/lib -lR
/usr/bin/ld: cannot find -lgfortran
collect2: error: ld returned 1 exit status
/usr/share/R/share/make/shlib.mk:6: recipe for target 'SparseM.so' failed

$ find /usr/lib -name '*fort*'
/usr/lib/x86_64-linux-gnu/libgfortran.so
/usr/lib/x86_64-linux-gnu/libgfortran.so.5
/usr/lib/x86_64-linux-gnu/libgfortran.so.5.0.0
/usr/lib/gcc/x86_64-linux-gnu/8/libgfortran.so
/usr/lib/gcc/x86_64-linux-gnu/8/libgfortran.a
/usr/lib/gcc/x86_64-linux-gnu/8/libgfortran.spec
/usr/lib/google-cloud-sdk/lib/third_party/pygments/lexers/fortran.pyc
/usr/lib/google-cloud-sdk/lib/third_party/pygments/lexers/fortran.py
/usr/lib/google-cloud-sdk/lib/third_party/pygments/lexers/forth.py
/usr/lib/google-cloud-sdk/lib/third_party/pygments/lexers/forth.pyc

$ ls -l /usr/lib/x86_64-linux-gnu/libgfortran*
lrwxrwxrwx 1 root root      42 May 29 21:40 /usr/lib/x86_64-linux-gnu/libgfortran.so -> /usr/lib/x86_64-linux-gnu/libgfortran.so.3
lrwxrwxrwx 1 root root      20 Apr  6 14:44 /usr/lib/x86_64-linux-gnu/libgfortran.so.5 -> libgfortran.so.5.0.0
-rw-r--r-- 1 root root 2541880 Apr  6 14:44 /usr/lib/x86_64-linux-gnu/libgfortran.so.5.0.0
```

So the problem is that #710 linked to a specific version of the shared library (libgfortran.so.3) which is not present anymore.

**Comment by mbookman** [comment] 2019-06-28 19:06
@rtitle - Are there any workarounds to this?

**Comment by rtitle** [comment] 2019-06-28 19:15
Agreed the link is broken. I helped another user with this and we worked around it with a user script. Can you check out gs://rtitle_test/fortran.sh and see if that resolves it?

This should be fixed in the base image - it might have fallen through the cracks. @sharmatime we should make a JIRA to fix fortran in the Leo image.

**Comment by rtitle** [comment] 2019-06-28 19:20
Ah it’s already in Jira. See https://broadworkbench.atlassian.net/browse/IA-1002

**Comment by mbookman** [comment] 2019-06-28 21:01
I recreated my cluster, setting the "Startup script" to `gs://rtitle_test/fortran.sh`.

The link looks good:

```
$ ls -l /usr/lib/x86_64-linux-gnu/*fortran*
lrwxrwxrwx 1 root root      42 Jun 28 20:32 /usr/lib/x86_64-linux-gnu/libgfortran.so -> /usr/lib/x86_64-linux-gnu/libgfortran.so.5
lrwxrwxrwx 1 root root      20 Apr  6 14:44 /usr/lib/x86_64-linux-gnu/libgfortran.so.5 -> libgfortran.so.5.0.0
-rw-r--r-- 1 root root 2541880 Apr  6 14:44 /usr/lib/x86_64-linux-gnu/libgfortran.so.5.0.0
```

and installing packages has gone smoothly.

Thanks Rob!

**Closed** 2020-03-18 14:10 UTC
Labels: RC_K_2019-01-03
