### ISSUE TITLE
Create Jenkins build to periodically clean up clusters 

### ISSUE THREAD

**Issue by kyuksel** [DataBiosphere/leonardo#402] opened 2018-06-01 18:34 UTC
...that were created as part of tests and not cleaned up.

**Comment by vkumra-broad** [comment] 2018-06-04 17:27
I gave this a shot and it doesn't seem to be as straightforward as I thought. 

Ran into issues with passing the credentials to the jenkins job. It would need SA credentials we currently run the script as: 

```./cleanup_clusters.sh delete qa thibault@quality.firecloud.org```

**Comment by MatthewBemis** [comment] 2019-05-08 22:25
closing as duplicate of https://github.com/DataBiosphere/leonardo/issues/243

**Closed by MatthewBemis** 2019-05-08 22:25 UTC
Labels: P3
