### ISSUE TITLE
Expose error details when cluster.status is "Error"

### ISSUE THREAD

**Issue by calbach** [DataBiosphere/leonardo#225] opened 2018-02-28 23:43 UTC
In the prod notebook env - `createCluster()` returned, but the cluster entered the error state. ~~Need help diagnosing what happened here.~~

```
GET /clusters => [{
   ...
    "googleProject": "aou-test-f1-1557534645",
    "status": "Error",
    "clusterName": "calbach123452",
   "jupyterUserScriptUri": ...,
    ...
  }, ...]
```

One thing to note is that I provided a user script. That user script worked fine on a local install of Leonardo.

**Comment by calbach** [comment] 2018-02-28 23:47
Actually I suspect this may have been a permission error, my SA did not have bucket access (though the script object itself is public). Confirming this now.

If that's what happened, possibly this could be an enhancement request to expose some information about initialization errors.

**Comment by calbach** [comment] 2018-02-28 23:54
Confirmed it was the above issue; renamed issue accordingly.

**Comment by rtitle** [comment] 2018-03-07 19:38
I believe this is a dupe of https://github.com/DataBiosphere/leonardo/issues/141, which is currently on dev.

**Closed** 2018-03-14 14:49 UTC
