### ISSUE TITLE
Refactor SamServiceAccountProvider to use Swagger sam client instead of sam DAO

### ISSUE THREAD

**Issue by vkumra-broad** [DataBiosphere/leonardo#173] opened 2018-02-01 19:59 UTC
Refactor SamServiceAccountProvider to use Swagger sam client instead of httpSamDAO

**Comment by rtitle** [comment] 2018-02-08 16:52
Duplicate of https://github.com/DataBiosphere/leonardo/issues/164

**Closed by rtitle** 2018-02-08 16:52 UTC
Labels: housekeeping
