### ISSUE TITLE
Direct JupyterLab notebook URLs don't work with Leo

### ISSUE THREAD

**Issue by danqrodney** [DataBiosphere/leonardo#474] opened 2018-07-12 16:16 UTC
If you right-click on a file in the files viewer in JupyterLab, there's a "Copy Shareable Link" option which generates URLs that you're supposed to be able to use to open a notebook directly. 

This works fine when running locally. But the links don't work with Leo. An example generated URL in dev is:

https://leonardo.dsde-dev.broadinstitute.org/notebooks/aou-rw-local1-2116819717/all-of-us/lab/tree/workspaces%2Fblargen%2FUntitled.ipynb

If you try to use this directly, you get a 404. If you change %2F in both places to /, you no longer get a 404, but it doesn't actually open the notebook if it's not already opened in your JupyterLab session.

We'd like to switch to using JupyterLab in All of Us, but need to be able to open notebooks for the current workspace directly from the workbench UI... presumably by redirecting to URLs like these.

@rtitle @calbach

**Comment by vkumra-broad** [comment] 2018-08-06 21:21
I couldn't reproduce this error, I clicked on "Copy Shareable Link" and got the following when I copied the link in a new tab.

![image](https://user-images.githubusercontent.com/30244225/43741516-aef7a4da-999c-11e8-971c-b9ecb00b7298.png)

When I closed the previous JupyterLab and pasted the link in a new tab it worked fine. 

I didn't see any issues with the link either, this is the copied link 

https://leonardo-fiab.dsde-dev.broadinstitute.org:30443/notebooks/vk-test-16/vk-test-3/lab/tree/Untitled1.ipynb

**Comment by rtitle** [comment] 2018-08-07 15:54
@vkumra-broad in Dan's example the notebook was in a subdirectory. Did you test that case? E.g. 

https://leo/notebooks/project/cluster/lab/tree/workspaces/my-workspace/Untitled1.ipynb

**Comment by calbach** [comment] 2018-08-07 16:49
Also may be worth testing with spaces in the notebook name - we've been burned a few times by that particular issue (apparently this is actually the majority preference for our beta users).

**Comment by vkumra-broad** [comment] 2018-08-07 17:09
I haven't, I'll try those cases today

**Comment by danqrodney** [comment] 2018-08-17 18:51
@vkumra-broad  Any update on this?

**Comment by vkumra-broad** [comment] 2018-08-21 21:07
No I haven't had a chance to look any further into it yet. I was able to replicate the issue with subdirectories though.

**Comment by rtitle** [comment] 2018-08-21 21:59
@danqrodney I did some investigation. This page has good background information: https://jupyterlab.readthedocs.io/en/stable/user/urls.html

The "Copy shareable link" option in JupyterLab incorrectly URL-encodes the notebook when it's in a subdirectory, so it doesn't work. But I am able to open notebooks directly using this URL scheme:

# opens my-ws/notebook.ipynb
https://notebooks.firecloud.org/notebooks/broad-firecloud-dsde/rt-lab-test/lab/tree/my-ws/notebook.ipynb

It works even in Incognito where I don't have a saved session.

There's a wrinkle, however. JupyterLab has the notion of "workspaces" which persist the state of your session (layout, tabs, etc). You can only have 1 workspace open in a tab at a time. If you omit the workspace in the URL it uses the "default" workspace, but based on the docs you can specify other workspaces like "https://.../lab/workspaces/foo". HOWEVER, this doesn't seem to be working, at least in Leo. If I specify a workspace like this: https://notebooks.firecloud.org/notebooks/broad-firecloud-dsde/rt-lab-test/lab/workspaces/foobar it complains that the `foobar` workspace is already in use (it's not) and prompts me to create a new one. If I create a new one, then the redirect doesn't work.

So the takeaway is that direct links to notebooks seem to be working using the `.../lab/tree/<path>` format specified above. But there's a limitation that you can only have JupyterLab open in 1 tab at a time. How important is that second point to AllOfUs? We can try to investigate the issues with JupyterLab workspaces a bit more, I'm just not sure if it's a blocker.

**Comment by danqrodney** [comment] 2018-08-21 22:05
I'm not sure how important it is to have multiple JupyterLab tabs open at once, though we should look into this more.

So to clarify: you're saying that if we follow the right URL scheme, direct links should work... it's just that the "Copy shareable link" URLs that get generated are wrong when they are in subdirectories?

I thought I had tried URLs without escaping the slashes (like you have above) but perhaps I did it wrong...

**Comment by rtitle** [comment] 2018-08-21 22:08
> So to clarify: you're saying that if we follow the right URL scheme, direct links should work... it's just that the "Copy shareable link" URLs that get generated are wrong when they are in subdirectories?
That's correct.

> I thought I had tried URLs without escaping the slashes (like you have above) but perhaps I did it wrong...
I'm testing it now and it seems ok. Perhaps you had 2 tabs open with JupyerLab when you were testing? I have to keep remembering to close my old tab...

**Comment by rtitle** [comment] 2018-08-21 22:16
Hm here's another potential issue.

1. I load this URL in an incognito window (after setting the cookie):
```
https://notebooks.firecloud.org/notebooks/broad-firecloud-dsde/rt-lab-test/lab/tree/workspace/notebook2.ipynb
```
2. It opens Lab with the notebook open, but it changes the browser URL to:
```
https://notebooks.firecloud.org/lab/notebooks/broad-firecloud-dsde/rt-lab-test
```
This is weird because the `/lab` is in the wrong place -- it is in the beginning when it should be at the end. The consequence is that refreshing the page does not work.

This is probably not ideal -- I will investigate this more.

**Comment by akarukappadath** [comment] 2018-09-18 15:13
Here's a quick tech doc explaining what we've learned about this issue: https://docs.google.com/document/d/1L3KPlG-HDcHFEEma6YDwXrw1U8S9f_c0FC5reYbuGRc/edit

At least one of the issues will be resolved by updating JupyterLab, which cannot be done until python is also updated, so we will revisit this after fixing the Dockerfile issue.

**Closed** 2018-12-04 21:52 UTC
Labels: AoU, P1, RC_K_2018-12-04, bug
