### ISSUE TITLE
Jupyter terminal freezes updating after two minutes

### ISSUE THREAD

**Issue by helgridly** [DataBiosphere/leonardo#546] opened 2018-08-27 18:15 UTC
Noticed this while running `top` in a terminal to watch a different one.

1. Run top. Note the time in the top left of the output.
2. Wait. I tend to wander off to different tabs during this time, so I'm not sure this happens while you're watching.
3. Two minutes later, output freezes (notice the clock is no longer updating).

Chrome 68.0.3440.84, `broad-firecloud-dsde-methods/hussein2`

Refreshing the page fixes it (for another two minutes). Console has an error:

```
WebSocket is already in CLOSING or CLOSED state.
window.onresize @ main.js:56
```

**Comment by rtitle** [comment] 2018-08-27 18:42
I just reproduced this. After a couple minutes the terminal froze and I saw this in the console log:
```
terminado.js:9 WebSocket is already in CLOSING or CLOSED state.
```

 Note google_sign_in.js has a timer to ping Leo every 2 minutes to prevent auto-freeze when the notebook is open. I wonder if this AJAX request is somehow killing the websocket? I am not sure how/why it would be doing that, but something to investigate...

**Comment by rtitle** [comment] 2018-08-28 15:52
So I think this is the same cause as https://github.com/DataBiosphere/leonardo/issues/547, which should be fixed in prod shortly. I retested the terminal on dev after the fix and the freeze did not occur.

**Comment by rtitle** [comment] 2018-08-29 14:55
We pushed the LB fix to prod last night, and the issue seems to be resolved. I successfully ran kernels last night for 3+ hours until they died (which could have been due to some other reason -- I'm still investigating this). I'm closing this ticket since the original issue is resolved. Rob M and I are continuing to look into networking settings though to ensure that long-lived kernels stay open.

**Closed by rtitle** 2018-08-29 14:55 UTC
Labels: P1
